// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRuNrq1nSKbRiUqQgDEO9hmliY5m-8VHY',
    appId: '1:752097838897:web:40e9ca37fff4cc2259d210',
    messagingSenderId: '752097838897',
    projectId: 'sagor-project-2-1',
    authDomain: 'sagor-project-2-1.firebaseapp.com',
    storageBucket: 'sagor-project-2-1.appspot.com',
    measurementId: 'G-JYKEXL3BMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALruPw69cnwnvcsIH78Zof__eQXFqtpio',
    appId: '1:752097838897:android:864589117598290259d210',
    messagingSenderId: '752097838897',
    projectId: 'sagor-project-2-1',
    storageBucket: 'sagor-project-2-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-fgWE2IIAaFIqOgRMi-diG2fB1SyYFbc',
    appId: '1:752097838897:ios:16f27095114b8cd259d210',
    messagingSenderId: '752097838897',
    projectId: 'sagor-project-2-1',
    storageBucket: 'sagor-project-2-1.appspot.com',
    iosBundleId: 'com.example.sagorProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-fgWE2IIAaFIqOgRMi-diG2fB1SyYFbc',
    appId: '1:752097838897:ios:16f27095114b8cd259d210',
    messagingSenderId: '752097838897',
    projectId: 'sagor-project-2-1',
    storageBucket: 'sagor-project-2-1.appspot.com',
    iosBundleId: 'com.example.sagorProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRuNrq1nSKbRiUqQgDEO9hmliY5m-8VHY',
    appId: '1:752097838897:web:67992dbfcd95b0a659d210',
    messagingSenderId: '752097838897',
    projectId: 'sagor-project-2-1',
    authDomain: 'sagor-project-2-1.firebaseapp.com',
    storageBucket: 'sagor-project-2-1.appspot.com',
    measurementId: 'G-NK77EQG0R7',
  );
}
